# Generated by Django 6.0.7 on 2026-07-28 22:50

import accounts.models
import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', accounts.models.ScopedUserManager()),
                ('unscoped_for_auth', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
