# Generated by Django 6.0.7 on 2026-07-28 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(blank=True, choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('en_preparacion', 'En preparación'), ('listo', 'Listo'), ('en_camino', 'En camino'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado'), ('sin_stock', 'Sin stock'), ('rechazado', 'Rechazado')], max_length=20, null=True)),
                ('estado_nuevo', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('en_preparacion', 'En preparación'), ('listo', 'Listo'), ('en_camino', 'En camino'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado'), ('sin_stock', 'Sin stock'), ('rechazado', 'Rechazado')], max_length=20)),
                ('actor', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='orders.order')),
            ],
        ),
    ]
