# Generated by Django 6.0.7 on 2026-07-31 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_pairingcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='horarios',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='tenant',
            name='medios_pago',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='tenant',
            name='ubicacion',
            field=models.TextField(blank=True, default=''),
        ),
    ]
