# Generated by Django 6.0.7 on 2026-07-31 22:04

import django.db.models.deletion
import tenants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_tenant_horarios_tenant_medios_pago_tenant_ubicacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=tenants.models._generate_bot_token, max_length=64, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_tokens', to='tenants.tenant')),
            ],
        ),
    ]
